### PR TITLE
Install Packer

### PR DESCRIPTION
**Pull request by evilmarty**

### CODE REVIEW

**Comment by toolmantim** [comment]
Whoops, accidental public pull request?

**Comment by evilmarty** [comment]
Yes. Sorry abouy that, the GH UI failed me and went to this repo instead of our own.

**Comment by toolmantim** [comment]
No sweat! If you want me to email GH support to delete, happy to

**Comment by lox** [comment]
I'd love to get some of those changes into master @evilmarty, let us know if you ever feel inclined to discuss your usecase and how we might upstream some of the things you need.

**Comment by evilmarty** [comment]
@lox definitely. Just trying to complete things on our end and wrap up the pipeline and I'll introduce those changes as bite-size chunks.

**Pull request closed without merging**
