### PR TITLE
Single buildkite-agent on host for easier autoscaling

### PR DESCRIPTION
**Pull request by lox**
This fundamentally changes how buildkite-aws-stack works by retreating from the idea of running many bk agents on a single docker host to a single buildkite agent running directly on the host. A customized AMI is built to speed up autoscaling operations.

### CODE REVIEW

**Comment by lox** [comment]
Ok, this is happening.

**Comment by toolmantim** [comment]
I endorse this lack of magic :tada:

**Comment by lox** [comment]
Somehow in the process of simplifying I've added more code.

**Comment by toolmantim** [comment]
Don't forget all the code inside the moving parts we're removing :)

**Pull request merged**
