### PR TITLE
Remove "LTS" from the AMI release tag

### PR DESCRIPTION
**Pull request by dgoodlad**
According to [Ubuntu](https://wiki.ubuntu.com/LTS), 15.04 isn't an LTS release; 15.10 will be.

### CODE REVIEW

**Comment by pda** [comment]
LTS is scheduled every two years (every fourth release), the most recent being 14.04 and the next being 16.04… unless there's some big changes I'm not seeing.

So yeah… :+1: for this PR removing it, but :-1: for 15.10 being the next :wink:

**Comment by daveslutzkin** [comment]
:+1: for @pda's reasoning

**Comment by dgoodlad** [comment]
>  :-1: for 15.10 being the next

:joy: Fight the good fight, @pda!

**Comment by lox** [comment]
Ugh, my bad. For some reason I thought that all .04's were LTS. From that graph, 16.04 is the next LTS, right?

**Pull request merged**
